[ServerSettings]

; ================================================================
; TASAS BASE
; ================================================================
XPMultiplier=7.0
TamingSpeedMultiplier=10.0
HarvestAmountMultiplier=10.0

MatingIntervalMultiplier=0.16667
EggHatchSpeedMultiplier=100.0
BabyMatureSpeedMultiplier=100.0

; ================================================================
; EVENTOS DE FIN DE SEMANA
; ================================================================

;MatingIntervalMultiplier=0.1
;EggHatchSpeedMultiplier=200.0
;BabyMatureSpeedMultiplier=200.0

;XPMultiplier=14.0
;TamingSpeedMultiplier=20.0
;HarvestAmountMultiplier=10.0
